from PyQt6 import QtWidgets, QtCore
class Find(QtWidgets.QDialog):
    def __init__(self):
        super().__init__() 
        self.setWindowFlags(QtCore.Qt.WindowType.Window | 
        QtCore.Qt.WindowType.CustomizeWindowHint | 
        QtCore.Qt.WindowType.WindowStaysOnTopHint | 
        QtCore.Qt.WindowType.WindowCloseButtonHint)
        self.setWindowTitle('Find')
        self.setFixedSize(400,200)
        self.horizontal_layout = QtWidgets.QHBoxLayout(self)
        self.frame_2 = QtWidgets.QFrame(self)
        self.vertical_layout = QtWidgets.QVBoxLayout(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.label = QtWidgets.QLabel("Find what", self.frame_4)
        self.line_edit = QtWidgets.QLineEdit("", self.frame_4)
        self.horizontal_layout_2.addWidget(self.label)
        self.horizontal_layout_2.addWidget(self.line_edit) 
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.horizontal_layout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("padding: 0px")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.check_box = QtWidgets.QCheckBox("Match case", self.frame_6)
        self.check_box_2 = QtWidgets.QCheckBox("Wrap around", self.frame_6)
        self.vertical_layout_3.addWidget(self.check_box, alignment= QtCore.Qt.AlignmentFlag.AlignBottom)
        self.vertical_layout_3.addWidget(self.check_box_2, alignment= QtCore.Qt.AlignmentFlag.AlignBottom)
        self.group_box = QtWidgets.QGroupBox(self.frame_5)
        self.group_box.setTitle("Direction")
        self.horizontal_layout_4 = QtWidgets.QHBoxLayout(self.group_box)
        self.radio_button = QtWidgets.QRadioButton("Up", self.group_box)
        self.radio_button_2 = QtWidgets.QRadioButton("Down", self.group_box)
        self.radio_button_2.setChecked(True)
        self.horizontal_layout_4.addWidget(self.radio_button)
        self.horizontal_layout_4.addWidget(self.radio_button_2)
        self.horizontal_layout_3.addWidget(self.frame_6, alignment= QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontal_layout_3.addWidget(self.group_box, alignment= QtCore.Qt.AlignmentFlag.AlignTop)
        self.vertical_layout.addWidget(self.frame_4)       
        self.vertical_layout.addWidget(self.frame_5)     
        self.frame_3 = QtWidgets.QFrame(self)
        self.vertical_layout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.push_button = QtWidgets.QPushButton("Find Next", self)
        self.push_button_2 = QtWidgets.QPushButton("Cancel")
        self.vertical_layout_2.addWidget(self.push_button)
        self.vertical_layout_2.addWidget(self.push_button_2)
        self.horizontal_layout.addWidget(self.frame_2)
        self.horizontal_layout.addWidget(self.frame_3, alignment= QtCore.Qt.AlignmentFlag.AlignTop)

